"""Rebuild the offline design-system artifact from the production design assets."""
from pathlib import Path
import base64
import html
import json
import re

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parents[1] / 'cloudflare-site' / 'assets'

def inline_asset(match):
    path = ASSETS / match.group(1)
    mime = 'font/woff2' if path.suffix == '.woff2' else 'image/svg+xml'
    return 'url("data:' + mime + ';base64,' + base64.b64encode(path.read_bytes()).decode() + '")'

styles = '\n'.join((ASSETS / name).read_text() for name in ['fonts/fonts.css', 'site.css', 'imagony-motion.css'])
styles = re.sub(r'url\([\"\']?/assets/([^\"\')]+)[\"\']?\)', inline_asset, styles)
tokens = json.loads((HERE / 'tokens.json').read_text())['tokens']
names = ['void', 'onyx', 'slate', 'iris', 'violet', 'cobalt', 'steel', 'haze', 'fog', 'paper', 'ink', 'iris-deep']
swatches = ''.join('<article class="swatch"><div style="background:var(--'+name+')"></div><strong>'+name+'</strong><code>'+html.escape(tokens[name]['value'])+'</code></article>' for name in names)
body = '''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Imagony · Design System v1</title><style>STYLES
.system-head{padding:32px 0;border-bottom:1px solid var(--line)}.system-head .brand{color:var(--haze)}.system-intro{display:grid;grid-template-columns:1.1fr .8fr;gap:6%;padding:70px 0}.system-intro h1{font-size:var(--fs-display)}.system-intro .prism{align-self:center}.system-section{padding:60px 0;border-top:1px solid var(--line)}.system-section h2{font-size:var(--fs-h3)}.system-section p{max-width:760px;color:var(--haze-2)}.swatches{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:30px 0}.swatch{background:var(--slate);padding:16px;min-width:0}.swatch>div{height:90px;clip-path:polygon(0 0,calc(100% - 14px) 0,100% 14px,100% 100%,14px 100%,0 calc(100% - 14px));border:1px solid var(--line)}.swatch strong,.swatch code{display:block;margin-top:8px}.system-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.system-mono{font-family:var(--font-mono);color:var(--iris);letter-spacing:.1em}.type-display{font-size:clamp(2.5rem,5vw,4.5rem);font-stretch:112%;font-weight:600;line-height:1.04}.system-section .button{margin:0 12px 16px 0}.light-sample{background:var(--fog);color:var(--ink);padding:36px;clip-path:polygon(0 0,calc(100% - 28px) 0,100% 28px,100% 100%,28px 100%,0 calc(100% - 28px))}.light-sample p{color:var(--ink-2)}.light-sample a{color:var(--iris-deep)}.system-note{color:var(--steel);font-size:.875rem}details{border-top:1px solid var(--line);padding:18px 0}summary{cursor:pointer;font-weight:600}table{width:100%;border-collapse:collapse}td,th{padding:14px 8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}footer{padding:40px 0;color:var(--steel)}@media(max-width:700px){.system-intro,.system-grid{grid-template-columns:1fr}.system-intro{padding:45px 0}.system-intro .prism{max-width:330px}.swatches{grid-template-columns:1fr 1fr}table{font-size:.85rem}td,th{padding:10px 4px}}
</style></head><body><header class="system-head shell"><a class="brand" href="#main"><span class="brand-mark" aria-hidden="true"></span> IMAGONY</a></header><main id="main" class="shell"><section class="system-intro"><div><p class="kicker">Design System / v1 / 26.09.2026</p><h1>Prisma.<br>Fase.<br>Facetten.</h1><p class="lead">Eine eigenständige Ableitung der navyra-Designgrammatik für Imagony. Diese Datei enthält Schriften, Komponenten und Bewegung und lässt sich offline öffnen.</p><a class="button primary" href="#components">Komponenten ansehen ↗</a></div><div class="prism prism-float" data-prism aria-hidden="true"></div></section>
<section class="system-section"><p class="kicker">01 / Grammatik</p><h2>Sechs Prinzipien.</h2><details open><summary>Die Seite ist ohne Animation vollständig.</summary><p>Bewegung gibt Rückmeldung. Das Prisma ist die einzige dauerhafte Animation; mit reduzierter Bewegung bleibt es statisch.</p></details><details><summary>Ein grosses, angeschnittenes Motiv.</summary><p>Ein offenes Dreieck aus drei facettierten Balken ersetzt die Schleife. Geometrie mit Seed 11; 120 Facetten.</p></details><details><summary>Fase statt Rundung.</summary><p>Oben rechts und unten links: 10, 14, 28 oder 40 Pixel. Flächen bleiben kantig und ohne Schatten.</p></details><details><summary>Licht kommt aus dem Motiv.</summary><p>Violet und Cobalt dienen als Lichtfarben. Lesbarer Text verwendet Iris auf dunkel oder Iris-Deep auf hell.</p></details><details><summary>Eine Hauptschrift, eine Nebenschrift.</summary><p>Archivo für Inhalte; IBM Plex Mono für Navigation, Etiketten, Nummern und Ticker. Beide Schriften werden unter OFL lokal eingebunden.</p></details><details><summary>Linksbündig, grosse Abstände, ein Textakzent.</summary><p>Eine ruhige Ordnung hält die fachlichen Inhalte und menschlichen Zuständigkeiten lesbar.</p></details></section>
<section class="system-section"><p class="kicker">02 / Farbe</p><h2>Void bis Iris.</h2><p>Violet und Cobalt sind keine Textfarben. Der helle Bereich nutzt Ink, Ink-2 und Iris-Deep.</p><div class="swatches">SWATCHES</div><div class="light-sample"><h3>Die helle Leistungsebene.</h3><p>Fog als Grund, Paper für Karten und Ink für Inhalte.</p><a href="#components">Iris-Deep als Linkakzent ↗</a></div></section>
<section class="system-section"><p class="kicker">03 / Typografie</p><h2>Breite Thesen. Präzise Etiketten.</h2><p class="type-display">Find the work.<br>Know who acts.</p><p>Archivo 400 für Fliesstext, 600 für Thesen und Titel. Breite: 112 % für Display, 106 % für Kartentitel und 125 % für die Wortmarke.</p><div class="system-mono">IBM PLEX MONO / 400–500 / TRACKING 0.14 EM</div></section>
<section id="components" class="system-section"><p class="kicker">04 / Komponenten</p><h2>Flächen mit einer klaren Funktion.</h2><button class="button primary" type="button">Primärbutton ↗</button><button class="button secondary" type="button">Sekundärbutton ↗</button><button class="button secondary" type="button" disabled>Deaktiviert</button><p class="system-note">Klicken zeigt die Faltung; Tab zeigt den innenliegenden Fokusrahmen. Die Beispiele lösen keine Anfragen aus.</p><div class="system-grid"><article class="card"><span class="card-number">01 / HUMAN DESK</span><h3>Scoped human action.</h3><p>Slate-Fläche, Lichtkante, 40-Pixel-Fase und ein klarer Link.</p><a href="#motion">Bewegung ansehen ↗</a></article><article class="form-card"><h3>Formular und Fokus</h3><label for="sample-input">Beispielfeld</label><input id="sample-input" placeholder="Kein Versand, nur ein Designbeispiel"><label for="sample-select">Auswahl</label><select id="sample-select"><option>Human review</option><option>Human operations</option></select><label class="check-label"><input type="checkbox"> Beispiel einer Zustimmung</label></article></div></section>
<section id="motion" class="system-section"><p class="kicker">05 / Bewegung</p><h2>Falten als Rückmeldung.</h2><table><thead><tr><th>Moment</th><th>Ablauf</th><th>Dauer</th></tr></thead><tbody><tr><td>Prisma</td><td>Schwebt als einziges Dauermotiv; Klick faltet 14 nahe Facetten.</td><td>9 s / 920 ms</td></tr><tr><td>Button</td><td>Von aussen zur Mitte; Formularbutton kehrt zurück.</td><td>280 / 560 ms</td></tr><tr><td>Seitenwechsel</td><td>Dreiecke decken vom Klickpunkt zu; die neue Seite entfaltet vom selben Punkt.</td><td>640 / 720 ms</td></tr></tbody></table><p class="system-note">Der vollständige Seitenwechsel wird in der lokalen Site geprüft. Interne Abschnittslinks in diesem Dokument springen direkt. Externe Links und Downloads erhalten keinen Übergang.</p></section>
<section class="system-section"><p class="kicker">06 / Ableitung</p><h2>Vier Achsen, eine eigene Marke.</h2><table><thead><tr><th>Achse</th><th>Imagony</th></tr></thead><tbody><tr><td>Geometrie</td><td>Prisma, Fasen und Dreiecksfacetten</td></tr><tr><td>Typografie</td><td>Breite Archivo + IBM Plex Mono</td></tr><tr><td>Farbe</td><td>Void / Slate / Iris, Violet und Cobalt als Licht</td></tr><tr><td>Darstellung</td><td>Angeschnittenes Motiv, helle Leistungsebene, Faltübergänge</td></tr></tbody></table><p>Bewusste Abweichung von „Die Seite steht“: Nur das Prisma schwebt. Änderungen an navyra werden einzeln gegen diese Achsen geprüft und als neue Designversion übernommen.</p></section></main><footer class="shell">Referenz: imagony-design-v1.zip, 26.09.2026 · Eigenständiges Prüfdokument, kein Produkt-Deployment.</footer><script>MOTION</script></body></html>'''
motion=re.sub(r'</script',r'<\\/script',(ASSETS/'imagony-motion.js').read_text(),flags=re.I)
body=body.replace('STYLES',styles).replace('SWATCHES',swatches).replace('MOTION',motion)
(HERE/'system.html').write_text(body)
print('Built docs/design-v1/system.html with embedded local fonts and assets.')
